# Generated by Django 4.2.13 on 2024-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.URLField(default='http://placehold.it/900x300'),
        ),
    ]
