# Generated by Django 4.2.13 on 2024-07-29 22:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_commentpost_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commentPost',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
