# Generated by Django 4.2.13 on 2024-07-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
